Repository pnnl/ExaGO, pull requests merged in 2023-11, with the labels that each got.

#77 Update CMakeLists.txt to correctly configure PKG config path non destructively
  CMakeLists.txt
Labels: xSDK

#79 Fix manual typo
  docs/manual/getting_started.tex
  docs/manual/manual.pdf
Labels: documentation, manual

#70 Fix ignoring contingencies when the from bus number is greater than than to bus number
  src/ps/ps.cpp
Labels: scopflow
